finish diplom
SergeyMazurtsev/java-explore-with-me pull request #1
Opened 2022-10-25 09:57 UTC by SergeyMazurtsev

2022-10-26 20:18 UTC, EvgenyKoptubenko commented on server/src/main/java/ru/practicum/ewm/admin/AdminServiceImpl.java
> +        List<Event> events = eventRepository.findAll(commonService.getPagination(from, size, null))
Похоже тут вытаскиваются все ивенты из базы данных, а потом идет сортировка по пользователям и т.д. Нужно это делать на уровне базы данных. Вытаскивать всю базу в приложение нельзя. Либо подскажи что тут делается.

2022-10-26 20:19 UTC, EvgenyKoptubenko commented on server/src/main/java/ru/practicum/ewm/admin/AdminServiceImpl.java
> +        if (categories != null) {
Дублирование кода с классом EventServiceImpl

2022-10-26 20:21 UTC, EvgenyKoptubenko commented on server/src/main/java/ru/practicum/ewm/admin/AdminServiceImpl.java
> +        } catch (DataIntegrityViolationException e) {
DataIntegrityViolationException везде преобразуется в IntegrityViolationException. Куча копи паста. Почему нельзя было оставить один эксепшн, не дублировать кучу кода?

2022-10-26 20:22 UTC, EvgenyKoptubenko commented on server/src/main/java/ru/practicum/ewm/admin/AdminServiceImpl.java
> +        }
получение ивента дублируется из метода в метод

2022-10-26 20:24 UTC, EvgenyKoptubenko commented on server/src/main/java/ru/practicum/ewm/common/CommonService.java
> +        List<ViewStats> viewStats = statisticClient.getViewOfEvent(
огромный кусок кода снова скопирован.

2022-10-26 20:27 UTC, EvgenyKoptubenko commented on server/src/main/java/ru/practicum/ewm/events/mapper/EventMapper.java
> +        eventDtoOutShort.id(event.getId());
снова копи паст.

2022-10-26 20:29 UTC, EvgenyKoptubenko commented on server/src/main/java/ru/practicum/ewm/events/EventPublicController.java
> +        log.info("app = {}", app);
снова есть копи паст

2022-10-26 20:41 UTC, EvgenyKoptubenko commented on README.md
> +https://github.com/SergeyMazurtsev/java-explore-with-me/pull/1
В такой огромный проект нужно добавлять информацию как его запустить локально
Сейчас, если запустить из коробки, то java.lang.IllegalStateException: Service id not legal hostname (${STAT_SERVER_NAME})

2022-10-26 20:43 UTC, EvgenyKoptubenko commented on server/pom.xml
> +            <artifactId>spring-cloud-starter-netflix-ribbon</artifactId>
Для чего эта зависимость?

2022-10-26 20:50 UTC, EvgenyKoptubenko requested changes
Проект гигантский, дофига дублирования кода. Напиши еще, пожалуйста, как запускать проект локально. Желательно, чтобы он запускался по одной кнопке, была документация как его запускать.

2022-10-26 20:59 UTC, SergeyMazurtsev commented on server/src/main/java/ru/practicum/ewm/admin/AdminServiceImpl.java
> +        List<Event> events = eventRepository.findAll(commonService.getPagination(from, size, null))
Это особенность контракта задания. 
Есть много различных входящих параметров, согласно которых нужно "отсеивать" данных. И каждый из параметров (кроме пагинации) могут быть null. 
Таким образом, делать кучу разных видов запросов в базу исходя из ветвлений проверки на null различных параметров просто не получится. 
Поэтому принял решение выгрузить одну запрошенную страницу (Page) и уже работать сортировкой через stream по каждому из параметров.

2022-10-26 21:06 UTC, SergeyMazurtsev commented on server/src/main/java/ru/practicum/ewm/admin/AdminServiceImpl.java
> +        if (categories != null) {
Да. Это связано с тем, что в разных сервисах (AdminService и EventService), согласно запросов из контроллеров, достаются коллекции сущностей Event. А уже согласно условий запроса, можно (то есть в запросе это параметр может быть null) делать фильтрацию из этой коллекции только по id категории.

2022-10-26 21:10 UTC, SergeyMazurtsev commented on server/src/main/java/ru/practicum/ewm/admin/AdminServiceImpl.java
> +        } catch (DataIntegrityViolationException e) {
Согласно условий контракта в Swagger, ответ на ошибку должен содержать определенные параметры в сущности ApiError, в частности - message(). Текст этого сообщения приведен в Swagger. 
Если можно убрать эту кучу текста, я буду только рад! У меня итак один exception строго отвечает именно за отлов исключений DataIntegrityViolationException, связанных с базой. А передачу сообщения можно вообще сделать укороченным. 
Просто, на сколько я понял, есть контракт и нужно делать согласно него.

2022-10-26 21:13 UTC, SergeyMazurtsev commented on server/src/main/java/ru/practicum/ewm/admin/AdminServiceImpl.java
> +        }
Все верно. 
Потому что:
1. На входе только id ивента. 
2. Обязательно нужно проверять на наличие в базе ивента с таким id. 
3. А иначе как я буду осуществлять логику работы сервиса без самого ивента из базы?

2022-10-26 21:16 UTC, SergeyMazurtsev commented on server/src/main/java/ru/practicum/ewm/common/CommonService.java
> +        List<ViewStats> viewStats = statisticClient.getViewOfEvent(
Согласен, я могу выделить эти 6 строчек кода в отдельный метод в этом классе и делать на него обращение. 
Суть этого куска кода - обращение в сервис статистики для получения информации о просмотрах.

2022-10-26 21:22 UTC, SergeyMazurtsev commented on server/src/main/java/ru/practicum/ewm/events/mapper/EventMapper.java
> +        eventDtoOutShort.id(event.getId());
Почему это копи паст?
В данной строчке 46-53 идет маппинг в EventDtoOutShort. А в этом же маппере на строчке 70-77 идет маппинг в EventDtoOutFull. 
Это два разных Dto, в двух разных методах маппера. 
Сделать полностью через MapStruct не получится из-за особенностей перевода полей category, confirmedRequests, initiator.

2022-10-26 21:25 UTC, SergeyMazurtsev commented on server/src/main/java/ru/practicum/ewm/events/EventPublicController.java
> +        log.info("app = {}", app);
В данном случае, это логирование отправки информации на сервер статистики. 
Я могу это вывести в отдельный метод внутри контроллера, просто не видел смысла, потому как у нас всего два ендпоинта, которые отправляют информацию на сервер статистики.

2022-10-26 21:30 UTC, SergeyMazurtsev commented on README.md
> +https://github.com/SergeyMazurtsev/java-explore-with-me/pull/1
Запуск проекта из коробки возможен через docker-compose, и он запускается полноценно со всеми необходимыми внешними environment переменными. Все эти переменные учтены в docker-compose.yml

Для удобства я могу добавить всю это информацию в readme. 
Плюс, если всё таки нужно описать дополнительно запуск без докера, то это тоже возможно, то тогда придется внешне добавлять environment переменные, а также подключать DB postgres на определенный порт.

2022-10-26 21:38 UTC, SergeyMazurtsev commented on server/pom.xml
> +            <artifactId>spring-cloud-starter-netflix-ribbon</artifactId>
Эта зависимость для клиента OpenFeign. 
Добавил эту зависимость исходя из статьи: https://medium.com/nuances-of-programming/создание-rest-клиента-с-помощью-spring-cloud-openfeign-и-netflix-ribbon-ea25a165014f

2022-10-27 19:09 UTC, EvgenyKoptubenko approved these changes
Работа сделана хорошо. Спасибо.

2022-10-27 19:55 UTC, merged